name: cloud_sync
description: >
  A Dart library for synchronizing files between local and cloud storage using customizable metadata and file handlers, with progress callbacks and error handling.
version: 0.4.0-rc.2
repository: https://github.com/lamnhan066/cloud_sync
issue_tracker: https://github.com/lamnhan066/cloud_sync/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0
